spring:
  datasource.url: jdbc:h2:file:./camunda-h2-database
  liquibase:
    change-log: classpath:db/camunda-changelog.xml

camunda.bpm:
  database:
    schema-update: false
  admin-user:
    id: admin
    password: pw